// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// covariance_cal
Rcpp::List covariance_cal(arma::vec a, arma::vec b, arma::vec c, arma::vec d, arma::mat e, arma::ivec f, arma::ivec g, arma::mat h, arma::mat i, arma::vec j, arma::vec k, arma::vec l, arma::mat m, arma::mat n);
RcppExport SEXP _tAUCMNAR_covariance_cal(SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP dSEXP, SEXP eSEXP, SEXP fSEXP, SEXP gSEXP, SEXP hSEXP, SEXP iSEXP, SEXP jSEXP, SEXP kSEXP, SEXP lSEXP, SEXP mSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type c(cSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type d(dSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type e(eSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type f(fSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type g(gSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type h(hSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type i(iSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type j(jSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type l(lSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(covariance_cal(a, b, c, d, e, f, g, h, i, j, k, l, m, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tAUCMNAR_covariance_cal", (DL_FUNC) &_tAUCMNAR_covariance_cal, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_tAUCMNAR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
